### ISSUE TITLE
Subtitiles

### ISSUE THREAD

**Issue by felipsmartins** [luisbg/snappy#19]
Hi, all!

Is it the official Snappy repo? Or just a fork?
It would be nice if snappy 1.0 could automatically load *.srt subtitles. For now I just made a python script in order to load subtitles, as long as I know just a bit little of C lang.

**Comment by luisbg** [comment]
The official repository of snappy is in git.gnome.org
https://git.gnome.org/browse/snappy/

I could add picking up *.srt subtitles automatically if they match the same name as the movie file. It is a good idea. Will push it soon.

Thanks for the suggestion.

**Comment by felipsmartins** [comment]
Hi, Luis de Bethencourt!

In fact, I just have created this feature. and I made a PR on GNOME/Snappy repo. Could you check it? 
See: [https://github.com/GNOME/snappy/pull/1](https://github.com/GNOME/snappy/pull/1)


Thanks!

**Comment by luisbg** [comment]
Checked! Thank you very much :)

**Comment by felipsmartins** [comment]
I see. Thank so much!
